services:
  db:
    image: postgres:18.3-alpine3.23
    user: postgres
    restart: always
    healthcheck:
      test: "pg_isready -U username --dbname=tests"
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 3031:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_DB: tests
      POSTGRES_PASSWORD: password
    volumes:
      # Persistent data storage
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
