/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as TestsNewRouteImport } from './routes/tests.new'
import { Route as TestsTestIdRouteImport } from './routes/tests.$testId'
import { Route as MeResponsesRouteImport } from './routes/me.responses'
import { Route as TestsTestIdIndexRouteImport } from './routes/tests.$testId.index'
import { Route as TestsTestIdResponsesRouteImport } from './routes/tests.$testId.responses'
import { Route as TestsTestIdEditRouteImport } from './routes/tests.$testId.edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as TestsTestIdResponsesResponseIdRouteImport } from './routes/tests.$testId.responses.$responseId'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestsRoute,
} as any)
const TestsNewRoute = TestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TestsRoute,
} as any)
const TestsTestIdRoute = TestsTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => TestsRoute,
} as any)
const MeResponsesRoute = MeResponsesRouteImport.update({
  id: '/me/responses',
  path: '/me/responses',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestIdIndexRoute = TestsTestIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestsTestIdRoute,
} as any)
const TestsTestIdResponsesRoute = TestsTestIdResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => TestsTestIdRoute,
} as any)
const TestsTestIdEditRoute = TestsTestIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TestsTestIdRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestIdResponsesResponseIdRoute =
  TestsTestIdResponsesResponseIdRouteImport.update({
    id: '/$responseId',
    path: '/$responseId',
    getParentRoute: () => TestsTestIdResponsesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tests': typeof TestsRouteWithChildren
  '/me/responses': typeof MeResponsesRoute
  '/tests/$testId': typeof TestsTestIdRouteWithChildren
  '/tests/new': typeof TestsNewRoute
  '/tests/': typeof TestsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tests/$testId/edit': typeof TestsTestIdEditRoute
  '/tests/$testId/responses': typeof TestsTestIdResponsesRouteWithChildren
  '/tests/$testId/': typeof TestsTestIdIndexRoute
  '/tests/$testId/responses/$responseId': typeof TestsTestIdResponsesResponseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/me/responses': typeof MeResponsesRoute
  '/tests/new': typeof TestsNewRoute
  '/tests': typeof TestsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tests/$testId/edit': typeof TestsTestIdEditRoute
  '/tests/$testId/responses': typeof TestsTestIdResponsesRouteWithChildren
  '/tests/$testId': typeof TestsTestIdIndexRoute
  '/tests/$testId/responses/$responseId': typeof TestsTestIdResponsesResponseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tests': typeof TestsRouteWithChildren
  '/me/responses': typeof MeResponsesRoute
  '/tests/$testId': typeof TestsTestIdRouteWithChildren
  '/tests/new': typeof TestsNewRoute
  '/tests/': typeof TestsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tests/$testId/edit': typeof TestsTestIdEditRoute
  '/tests/$testId/responses': typeof TestsTestIdResponsesRouteWithChildren
  '/tests/$testId/': typeof TestsTestIdIndexRoute
  '/tests/$testId/responses/$responseId': typeof TestsTestIdResponsesResponseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/tests'
    | '/me/responses'
    | '/tests/$testId'
    | '/tests/new'
    | '/tests/'
    | '/api/auth/$'
    | '/tests/$testId/edit'
    | '/tests/$testId/responses'
    | '/tests/$testId/'
    | '/tests/$testId/responses/$responseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/me/responses'
    | '/tests/new'
    | '/tests'
    | '/api/auth/$'
    | '/tests/$testId/edit'
    | '/tests/$testId/responses'
    | '/tests/$testId'
    | '/tests/$testId/responses/$responseId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/tests'
    | '/me/responses'
    | '/tests/$testId'
    | '/tests/new'
    | '/tests/'
    | '/api/auth/$'
    | '/tests/$testId/edit'
    | '/tests/$testId/responses'
    | '/tests/$testId/'
    | '/tests/$testId/responses/$responseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  TestsRoute: typeof TestsRouteWithChildren
  MeResponsesRoute: typeof MeResponsesRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof TestsRoute
    }
    '/tests/new': {
      id: '/tests/new'
      path: '/new'
      fullPath: '/tests/new'
      preLoaderRoute: typeof TestsNewRouteImport
      parentRoute: typeof TestsRoute
    }
    '/tests/$testId': {
      id: '/tests/$testId'
      path: '/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof TestsTestIdRouteImport
      parentRoute: typeof TestsRoute
    }
    '/me/responses': {
      id: '/me/responses'
      path: '/me/responses'
      fullPath: '/me/responses'
      preLoaderRoute: typeof MeResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$testId/': {
      id: '/tests/$testId/'
      path: '/'
      fullPath: '/tests/$testId/'
      preLoaderRoute: typeof TestsTestIdIndexRouteImport
      parentRoute: typeof TestsTestIdRoute
    }
    '/tests/$testId/responses': {
      id: '/tests/$testId/responses'
      path: '/responses'
      fullPath: '/tests/$testId/responses'
      preLoaderRoute: typeof TestsTestIdResponsesRouteImport
      parentRoute: typeof TestsTestIdRoute
    }
    '/tests/$testId/edit': {
      id: '/tests/$testId/edit'
      path: '/edit'
      fullPath: '/tests/$testId/edit'
      preLoaderRoute: typeof TestsTestIdEditRouteImport
      parentRoute: typeof TestsTestIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$testId/responses/$responseId': {
      id: '/tests/$testId/responses/$responseId'
      path: '/$responseId'
      fullPath: '/tests/$testId/responses/$responseId'
      preLoaderRoute: typeof TestsTestIdResponsesResponseIdRouteImport
      parentRoute: typeof TestsTestIdResponsesRoute
    }
  }
}

interface TestsTestIdResponsesRouteChildren {
  TestsTestIdResponsesResponseIdRoute: typeof TestsTestIdResponsesResponseIdRoute
}

const TestsTestIdResponsesRouteChildren: TestsTestIdResponsesRouteChildren = {
  TestsTestIdResponsesResponseIdRoute: TestsTestIdResponsesResponseIdRoute,
}

const TestsTestIdResponsesRouteWithChildren =
  TestsTestIdResponsesRoute._addFileChildren(TestsTestIdResponsesRouteChildren)

interface TestsTestIdRouteChildren {
  TestsTestIdEditRoute: typeof TestsTestIdEditRoute
  TestsTestIdResponsesRoute: typeof TestsTestIdResponsesRouteWithChildren
  TestsTestIdIndexRoute: typeof TestsTestIdIndexRoute
}

const TestsTestIdRouteChildren: TestsTestIdRouteChildren = {
  TestsTestIdEditRoute: TestsTestIdEditRoute,
  TestsTestIdResponsesRoute: TestsTestIdResponsesRouteWithChildren,
  TestsTestIdIndexRoute: TestsTestIdIndexRoute,
}

const TestsTestIdRouteWithChildren = TestsTestIdRoute._addFileChildren(
  TestsTestIdRouteChildren,
)

interface TestsRouteChildren {
  TestsTestIdRoute: typeof TestsTestIdRouteWithChildren
  TestsNewRoute: typeof TestsNewRoute
  TestsIndexRoute: typeof TestsIndexRoute
}

const TestsRouteChildren: TestsRouteChildren = {
  TestsTestIdRoute: TestsTestIdRouteWithChildren,
  TestsNewRoute: TestsNewRoute,
  TestsIndexRoute: TestsIndexRoute,
}

const TestsRouteWithChildren = TestsRoute._addFileChildren(TestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  TestsRoute: TestsRouteWithChildren,
  MeResponsesRoute: MeResponsesRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
