/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests/index'
import { Route as TestsNewRouteImport } from './routes/tests/new'
import { Route as MeResponsesRouteImport } from './routes/me/responses'
import { Route as InvitationsTokenRouteImport } from './routes/invitations/$token'
import { Route as TestsTestIdIndexRouteImport } from './routes/tests/$testId/index'
import { Route as TestsTestIdEditRouteImport } from './routes/tests/$testId/edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as TestsTestIdResponsesIndexRouteImport } from './routes/tests/$testId/responses/index'
import { Route as TestsTestIdResponsesResponseIdRouteImport } from './routes/tests/$testId/responses/$responseId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsNewRoute = TestsNewRouteImport.update({
  id: '/tests/new',
  path: '/tests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MeResponsesRoute = MeResponsesRouteImport.update({
  id: '/me/responses',
  path: '/me/responses',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsTokenRoute = InvitationsTokenRouteImport.update({
  id: '/invitations/$token',
  path: '/invitations/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestIdIndexRoute = TestsTestIdIndexRouteImport.update({
  id: '/tests/$testId/',
  path: '/tests/$testId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestIdEditRoute = TestsTestIdEditRouteImport.update({
  id: '/tests/$testId/edit',
  path: '/tests/$testId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestIdResponsesIndexRoute =
  TestsTestIdResponsesIndexRouteImport.update({
    id: '/tests/$testId/responses/',
    path: '/tests/$testId/responses/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TestsTestIdResponsesResponseIdRoute =
  TestsTestIdResponsesResponseIdRouteImport.update({
    id: '/tests/$testId/responses/$responseId',
    path: '/tests/$testId/responses/$responseId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/me/responses': typeof MeResponsesRoute
  '/tests/new': typeof TestsNewRoute
  '/tests/': typeof TestsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tests/$testId/edit': typeof TestsTestIdEditRoute
  '/tests/$testId/': typeof TestsTestIdIndexRoute
  '/tests/$testId/responses/$responseId': typeof TestsTestIdResponsesResponseIdRoute
  '/tests/$testId/responses/': typeof TestsTestIdResponsesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/me/responses': typeof MeResponsesRoute
  '/tests/new': typeof TestsNewRoute
  '/tests': typeof TestsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tests/$testId/edit': typeof TestsTestIdEditRoute
  '/tests/$testId': typeof TestsTestIdIndexRoute
  '/tests/$testId/responses/$responseId': typeof TestsTestIdResponsesResponseIdRoute
  '/tests/$testId/responses': typeof TestsTestIdResponsesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/me/responses': typeof MeResponsesRoute
  '/tests/new': typeof TestsNewRoute
  '/tests/': typeof TestsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tests/$testId/edit': typeof TestsTestIdEditRoute
  '/tests/$testId/': typeof TestsTestIdIndexRoute
  '/tests/$testId/responses/$responseId': typeof TestsTestIdResponsesResponseIdRoute
  '/tests/$testId/responses/': typeof TestsTestIdResponsesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/invitations/$token'
    | '/me/responses'
    | '/tests/new'
    | '/tests/'
    | '/api/auth/$'
    | '/tests/$testId/edit'
    | '/tests/$testId/'
    | '/tests/$testId/responses/$responseId'
    | '/tests/$testId/responses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/invitations/$token'
    | '/me/responses'
    | '/tests/new'
    | '/tests'
    | '/api/auth/$'
    | '/tests/$testId/edit'
    | '/tests/$testId'
    | '/tests/$testId/responses/$responseId'
    | '/tests/$testId/responses'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/invitations/$token'
    | '/me/responses'
    | '/tests/new'
    | '/tests/'
    | '/api/auth/$'
    | '/tests/$testId/edit'
    | '/tests/$testId/'
    | '/tests/$testId/responses/$responseId'
    | '/tests/$testId/responses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  InvitationsTokenRoute: typeof InvitationsTokenRoute
  MeResponsesRoute: typeof MeResponsesRoute
  TestsNewRoute: typeof TestsNewRoute
  TestsIndexRoute: typeof TestsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  TestsTestIdEditRoute: typeof TestsTestIdEditRoute
  TestsTestIdIndexRoute: typeof TestsTestIdIndexRoute
  TestsTestIdResponsesResponseIdRoute: typeof TestsTestIdResponsesResponseIdRoute
  TestsTestIdResponsesIndexRoute: typeof TestsTestIdResponsesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/new': {
      id: '/tests/new'
      path: '/tests/new'
      fullPath: '/tests/new'
      preLoaderRoute: typeof TestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/responses': {
      id: '/me/responses'
      path: '/me/responses'
      fullPath: '/me/responses'
      preLoaderRoute: typeof MeResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token': {
      id: '/invitations/$token'
      path: '/invitations/$token'
      fullPath: '/invitations/$token'
      preLoaderRoute: typeof InvitationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$testId/': {
      id: '/tests/$testId/'
      path: '/tests/$testId'
      fullPath: '/tests/$testId/'
      preLoaderRoute: typeof TestsTestIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$testId/edit': {
      id: '/tests/$testId/edit'
      path: '/tests/$testId/edit'
      fullPath: '/tests/$testId/edit'
      preLoaderRoute: typeof TestsTestIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$testId/responses/': {
      id: '/tests/$testId/responses/'
      path: '/tests/$testId/responses'
      fullPath: '/tests/$testId/responses/'
      preLoaderRoute: typeof TestsTestIdResponsesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$testId/responses/$responseId': {
      id: '/tests/$testId/responses/$responseId'
      path: '/tests/$testId/responses/$responseId'
      fullPath: '/tests/$testId/responses/$responseId'
      preLoaderRoute: typeof TestsTestIdResponsesResponseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  InvitationsTokenRoute: InvitationsTokenRoute,
  MeResponsesRoute: MeResponsesRoute,
  TestsNewRoute: TestsNewRoute,
  TestsIndexRoute: TestsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  TestsTestIdEditRoute: TestsTestIdEditRoute,
  TestsTestIdIndexRoute: TestsTestIdIndexRoute,
  TestsTestIdResponsesResponseIdRoute: TestsTestIdResponsesResponseIdRoute,
  TestsTestIdResponsesIndexRoute: TestsTestIdResponsesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
