/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsNewRouteImport } from './routes/tests_.new'
import { Route as TestsTestIdRouteImport } from './routes/tests.$testId'
import { Route as MeResponsesRouteImport } from './routes/me.responses'
import { Route as TestsTestIdResponsesRouteImport } from './routes/tests_.$testId.responses'
import { Route as TestsTestIdEditRouteImport } from './routes/tests_.$testId.edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as TestsTestIdResponsesResponseIdRouteImport } from './routes/tests_.$testId.responses_.$responseId'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsNewRoute = TestsNewRouteImport.update({
  id: '/tests_/new',
  path: '/tests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestIdRoute = TestsTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => TestsRoute,
} as any)
const MeResponsesRoute = MeResponsesRouteImport.update({
  id: '/me/responses',
  path: '/me/responses',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestIdResponsesRoute = TestsTestIdResponsesRouteImport.update({
  id: '/tests_/$testId/responses',
  path: '/tests/$testId/responses',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestIdEditRoute = TestsTestIdEditRouteImport.update({
  id: '/tests_/$testId/edit',
  path: '/tests/$testId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestIdResponsesResponseIdRoute =
  TestsTestIdResponsesResponseIdRouteImport.update({
    id: '/tests_/$testId/responses_/$responseId',
    path: '/tests/$testId/responses/$responseId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tests': typeof TestsRouteWithChildren
  '/me/responses': typeof MeResponsesRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/tests/new': typeof TestsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tests/$testId/edit': typeof TestsTestIdEditRoute
  '/tests/$testId/responses': typeof TestsTestIdResponsesRoute
  '/tests/$testId/responses/$responseId': typeof TestsTestIdResponsesResponseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tests': typeof TestsRouteWithChildren
  '/me/responses': typeof MeResponsesRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/tests/new': typeof TestsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tests/$testId/edit': typeof TestsTestIdEditRoute
  '/tests/$testId/responses': typeof TestsTestIdResponsesRoute
  '/tests/$testId/responses/$responseId': typeof TestsTestIdResponsesResponseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tests': typeof TestsRouteWithChildren
  '/me/responses': typeof MeResponsesRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/tests_/new': typeof TestsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tests_/$testId/edit': typeof TestsTestIdEditRoute
  '/tests_/$testId/responses': typeof TestsTestIdResponsesRoute
  '/tests_/$testId/responses_/$responseId': typeof TestsTestIdResponsesResponseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/tests'
    | '/me/responses'
    | '/tests/$testId'
    | '/tests/new'
    | '/api/auth/$'
    | '/tests/$testId/edit'
    | '/tests/$testId/responses'
    | '/tests/$testId/responses/$responseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/tests'
    | '/me/responses'
    | '/tests/$testId'
    | '/tests/new'
    | '/api/auth/$'
    | '/tests/$testId/edit'
    | '/tests/$testId/responses'
    | '/tests/$testId/responses/$responseId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/tests'
    | '/me/responses'
    | '/tests/$testId'
    | '/tests_/new'
    | '/api/auth/$'
    | '/tests_/$testId/edit'
    | '/tests_/$testId/responses'
    | '/tests_/$testId/responses_/$responseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  TestsRoute: typeof TestsRouteWithChildren
  MeResponsesRoute: typeof MeResponsesRoute
  TestsNewRoute: typeof TestsNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  TestsTestIdEditRoute: typeof TestsTestIdEditRoute
  TestsTestIdResponsesRoute: typeof TestsTestIdResponsesRoute
  TestsTestIdResponsesResponseIdRoute: typeof TestsTestIdResponsesResponseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests_/new': {
      id: '/tests_/new'
      path: '/tests/new'
      fullPath: '/tests/new'
      preLoaderRoute: typeof TestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$testId': {
      id: '/tests/$testId'
      path: '/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof TestsTestIdRouteImport
      parentRoute: typeof TestsRoute
    }
    '/me/responses': {
      id: '/me/responses'
      path: '/me/responses'
      fullPath: '/me/responses'
      preLoaderRoute: typeof MeResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests_/$testId/responses': {
      id: '/tests_/$testId/responses'
      path: '/tests/$testId/responses'
      fullPath: '/tests/$testId/responses'
      preLoaderRoute: typeof TestsTestIdResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests_/$testId/edit': {
      id: '/tests_/$testId/edit'
      path: '/tests/$testId/edit'
      fullPath: '/tests/$testId/edit'
      preLoaderRoute: typeof TestsTestIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests_/$testId/responses_/$responseId': {
      id: '/tests_/$testId/responses_/$responseId'
      path: '/tests/$testId/responses/$responseId'
      fullPath: '/tests/$testId/responses/$responseId'
      preLoaderRoute: typeof TestsTestIdResponsesResponseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TestsRouteChildren {
  TestsTestIdRoute: typeof TestsTestIdRoute
}

const TestsRouteChildren: TestsRouteChildren = {
  TestsTestIdRoute: TestsTestIdRoute,
}

const TestsRouteWithChildren = TestsRoute._addFileChildren(TestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  TestsRoute: TestsRouteWithChildren,
  MeResponsesRoute: MeResponsesRoute,
  TestsNewRoute: TestsNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  TestsTestIdEditRoute: TestsTestIdEditRoute,
  TestsTestIdResponsesRoute: TestsTestIdResponsesRoute,
  TestsTestIdResponsesResponseIdRoute: TestsTestIdResponsesResponseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
